// Mocks generated by Mockito 5.4.6 from annotations
// in receipt_printing/test/services/summary_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:receipt_printing/database/order_dao.dart' as _i2;
import 'package:receipt_printing/models/order.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderDao extends _i1.Mock implements _i2.OrderDao {
  MockOrderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> insert(_i4.Order? order) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [order]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Order>> getByDate(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getByDate, [date]),
            returnValue: _i3.Future<List<_i4.Order>>.value(<_i4.Order>[]),
          )
          as _i3.Future<List<_i4.Order>>);

  @override
  _i3.Future<int> getOrderCountByDate(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderCountByDate, [date]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, int>> getDishCountByDate(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getDishCountByDate, [date]),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<int, int>> getHourlyDistribution(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getHourlyDistribution, [date]),
            returnValue: _i3.Future<Map<int, int>>.value(<int, int>{}),
          )
          as _i3.Future<Map<int, int>>);

  @override
  _i3.Future<int> getMaxTicketNumber(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#getMaxTicketNumber, [date]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<String>> getAvailableDates() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableDates, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}
